version: '2'
services:
    micham-app:
        image: micham
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://micham-postgresql:5432/micham
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8089:8089
    micham-postgresql:
        extends:
            file: postgresql.yml
            service: micham-postgresql
